Repository nyxx-discord/nyxx_interactions, pull requests merged in 2022-01, with the labels that each got.

#16 Fix typo
  lib/src/events/interaction_event.dart
Labels: bug

#18 A working version of the buttons and dropdowns example
  example/buttons_and_dropdowns.dart
Labels: bug, documentation

#20 bug: Fix invalid stream declarations of events in IEventController
  lib/src/internal/event_controller.dart
Labels: bug

#25 feature: implement interaction locale
  lib/src/models/interaction.dart
Labels: enhancement

#24 bug: Fix problem with emojis in buttons
  lib/src/builders/component_builder.dart
Labels: bug

#28 Add target_id field
  lib/src/models/interaction.dart
Labels: enhancement, blocked

#31 Implement guild_locale field on Interaction
  lib/src/models/interaction.dart
Labels: enhancement
