Repository nyxx-discord/nyxx_interactions, pull requests merged in 2022-11, with the labels that each got.

#64 Allow messages with only components to be used as new messages
  CHANGELOG.md
  lib/src/builders/component_builder.dart
  pubspec.yaml
Labels: bug

#62 feat: Add support for new select menus components
  .gitignore
  example/buttons_and_dropdowns.dart
  lib/nyxx_interactions.dart
  lib/src/builders/component_builder.dart
  lib/src/events/interaction_event.dart
  lib/src/interactions.dart
  lib/src/internal/event_controller.dart
  lib/src/internal/utils.dart
  lib/src/models/interaction.dart
  lib/src/models/interaction_data_resolved.dart
  lib/src/typedefs.dart
  pubspec.yaml
  test/unit/builder_test.dart
  test/unit/command_option_builder_test.dart
  test/unit/command_permission_builder_test.dart
  test/unit/command_sync_test.dart
  test/unit/component_builder_test.dart
  test/unit/event_controller_test.dart
  test/unit/model_test.dart
  test/unit/nyxx_backend_test.dart
  test/unit/slash_command_builder_test.dart
  test/unit/utils_test.dart
Labels: enhancement

#70 Handle HTTP error response in acknowledge()
  lib/src/events/interaction_event.dart
  lib/src/exceptions/already_responded.dart
Labels: enhancement

#69 Update nyxx_interactions to work with the new logging system in nyxx
  lib/src/events/interaction_event.dart
  lib/src/internal/interaction_endpoints.dart
Labels: bug, enhancement

#66 feat: Add support for nsfw commands
  lib/src/builders/slash_command_builder.dart
  lib/src/models/slash_command.dart
  test/unit/slash_command_builder_test.dart
Labels: enhancement

#71 fix slash command model failing with nsfw field
  test/unit/model_test.dart
Labels: bug
