Repository nyxx-discord/nyxx_interactions, pull requests merged in 2022-02, with the labels that each got.

#35 Clarify that getArg throws in ISlashCommandInteractionEvent
  lib/src/events/interaction_event.dart
Labels: documentation

#32 feature: modals
  lib/nyxx_interactions.dart
  lib/src/builders/component_builder.dart
  lib/src/builders/modal_builder.dart
  lib/src/events/interaction_event.dart
  lib/src/interactions.dart
  lib/src/internal/event_controller.dart
  lib/src/internal/interaction_endpoints.dart
  lib/src/models/interaction.dart
  lib/src/typedefs.dart
  pubspec.yaml
  test/unit/component_builder.dart
Labels: enhancement, blocked

#36 Fix ignoring shouldSync for guild command permissions
  CHANGELOG.md
  lib/src/interactions.dart
  pubspec.yaml
Labels: bug
